builds:
  - id: retrospec
    binary: retrospec
    main: ./cmd/retrospec
    goarch:
      - amd64
      - arm64
      - arm

archives:
  - id: retrospec
    builds:
      - retrospec
    format: zip
    name_template: 'retrospec_{{ .Version }}_{{- if eq .Os "darwin" }}macos{{- else }}{{ .Os }}{{ end }}_{{ .Arch }}'

